name: dogether_local_mysql

services:
  mysql:
    image: mysql:8.0
    container_name: dogether-mysql
    ports:
      - "33306:3306"
    volumes:
      - ./data/mysql/mysql:/var/lib/mysql
      - ./data/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dogether
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
